apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarqube-server-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /sonarqube-server
