apiVersion: v1
kind: Pod
metadata:
  name: temp-pod
  namespace: default
spec:
  containers:
    - name: temp-container
      image: busybox
      command: ["sleep", "3600"]
      volumeMounts:
        - name: storage-volume
          mountPath: /data
  volumes:
    - name: storage-volume
      persistentVolumeClaim:
        claimName: prometheus-server
  securityContext:
    fsGroup: 65534
