apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx-config
  namespace: nginx
data:
  nginx.conf: |
    events {}
    http {
        server {
            listen 80;
            server_name localhost;

            location /stub_status {
                stub_status;
                allow 127.0.0.1;  # Allow only internal access
                deny all;
            }

            # Other configurations...
            location / {
                root /usr/share/nginx/html;
                index index.html index.htm;
            }
        }
    }
