apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nginx
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: {{ .Values.service.nodePort }}
  selector:
    app: myapp
    type: front-end
